
import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sankhe
 */
public class AddStudentEntry extends javax.swing.JPanel {
	StudentModel studentModel;
	private static int id = 3;
	/**
	 * Creates new form AddStudentEntry
	 */
	public AddStudentEntry() {
		initComponents();
		Color c = new Color(183, 238, 242);
		setBackground(c);
		Border compound, raisedbevel, loweredbevel;
		raisedbevel = BorderFactory.createRaisedBevelBorder();
		loweredbevel = BorderFactory.createLoweredBevelBorder();
		Border redline = BorderFactory.createLineBorder(Color.yellow, 10);
		//This creates a nice frame.
		compound = BorderFactory.createCompoundBorder(raisedbevel, loweredbevel);
		setBorder(compound);
		//Add a red outline to the frame.
		compound = BorderFactory.createCompoundBorder(
				redline, compound);
		setBorder(compound);
		studentModel = MainFrame.getStudentModel();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		firstNameLabel = new javax.swing.JLabel();
		lastNameLabel = new javax.swing.JLabel();
		genderLabel = new javax.swing.JLabel();
		birthdateLabel = new javax.swing.JLabel();
		firstNameTextfield = new javax.swing.JTextField();
		lastNameTextfield = new javax.swing.JTextField();
		maleRadioButton = new javax.swing.JRadioButton();
		okButton = new javax.swing.JButton();
		clearButton = new javax.swing.JButton();
		femaleRadioButton = new javax.swing.JRadioButton();
		jButton1 = new javax.swing.JButton();
		ageLabel = new javax.swing.JLabel();
		ageTextField = new javax.swing.JTextField();
		birthdateTextField = new javax.swing.JTextField();

		setLayout(new java.awt.GridBagLayout());

		firstNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		firstNameLabel.setText("First Name");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.ipadx = 24;
		gridBagConstraints.ipady = 7;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(16, 51, 0, 0);
		add(firstNameLabel, gridBagConstraints);

		lastNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		lastNameLabel.setText("Last Name");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.ipadx = 26;
		gridBagConstraints.ipady = 7;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(17, 51, 0, 0);
		add(lastNameLabel, gridBagConstraints);

		genderLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		genderLabel.setText("Gender");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.ipadx = 41;
		gridBagConstraints.ipady = 7;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 51, 0, 0);
		add(genderLabel, gridBagConstraints);

		birthdateLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		birthdateLabel.setText("BirthDate");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.ipadx = 32;
		gridBagConstraints.ipady = 9;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(14, 51, 0, 0);
		add(birthdateLabel, gridBagConstraints);

		firstNameTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 152;
		gridBagConstraints.ipady = 14;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(14, 12, 0, 0);
		add(firstNameTextfield, gridBagConstraints);

		lastNameTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.ipadx = 152;
		gridBagConstraints.ipady = 14;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
		add(lastNameTextfield, gridBagConstraints);

		maleRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		maleRadioButton.setText("male");
		maleRadioButton.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				maleRadioButtonItemStateChanged(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
		add(maleRadioButton, gridBagConstraints);

		okButton.setBackground(new java.awt.Color(0, 0, 255));
		okButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		okButton.setText("OK");
		okButton.setToolTipText("click me to add student entry");
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 8;
		gridBagConstraints.gridwidth = 5;
		gridBagConstraints.ipadx = 58;
		gridBagConstraints.ipady = 16;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(27, 51, 0, 0);
		add(okButton, gridBagConstraints);

		clearButton.setBackground(new java.awt.Color(51, 51, 255));
		clearButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		clearButton.setText("Clear");
		clearButton.setToolTipText("click me to reset");
		clearButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearButtonActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 8;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.ipadx = 46;
		gridBagConstraints.ipady = 16;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(27, 57, 0, 0);
		add(clearButton, gridBagConstraints);

		femaleRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		femaleRadioButton.setText("female");
		femaleRadioButton.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				femaleRadioButtonItemStateChanged(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 19;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 2, 0, 0);
		add(femaleRadioButton, gridBagConstraints);

		jButton1.setBackground(new java.awt.Color(255, 0, 51));
		jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jButton1.setText("Back");
		jButton1.setToolTipText("click me to go back");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 9;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.ipadx = 33;
		gridBagConstraints.ipady = 12;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 70, 0, 10);
		add(jButton1, gridBagConstraints);

		ageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		ageLabel.setText("Age");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.ipadx = 38;
		gridBagConstraints.ipady = 6;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(14, 51, 0, 0);
		add(ageLabel, gridBagConstraints);

		ageTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		ageTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 152;
		gridBagConstraints.ipady = 13;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
		add(ageTextField, gridBagConstraints);

		birthdateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		birthdateTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.ipadx = 152;
		gridBagConstraints.ipady = 13;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
		add(birthdateTextField, gridBagConstraints);
	}// </editor-fold>                        

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here:
		resetAll();
	}  

	public void resetAll() {
		firstNameTextfield.setText("");
		lastNameTextfield.setText("");
		maleRadioButton.setSelected(false);
		femaleRadioButton.setSelected(false);
		ageTextField.setText("");
		birthdateTextField.setText("");
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		MainFrame.layCard.show(MainFrame.getTopPanel(), "2");
	}                                        

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		String[] array = new String[9];
		Student s1 = studentModel.getMaxIDFromDatabase();
		if(s1 == null) {
			array[0] = Integer.toString(1);
		} else {
			array[0] = Integer.toString(s1.getStudent_id())+1;
		}
		
		boolean flag = true;
		if(getFirstNameTextfield().getText().equals(""))
		{
			JOptionPane.showMessageDialog(this, "Please enter first name.",
					"Error Message", JOptionPane.ERROR_MESSAGE);
			flag = false;
		}
		else 
			array[1] = getFirstNameTextfield().getText();

		if(getLastNameTextfield().getText().equals(""))
		{
			JOptionPane.showMessageDialog(this, "Please enter last name.",
					"Error Message", JOptionPane.ERROR_MESSAGE);
			flag = false;
		}
		else 
			array[2] = getLastNameTextfield().getText();

		array[3] = valueSelectedRButton();
		if(getBirthdateTextField().getText().equals("")) 
			array[4] = "unknown";
		else
			array[4] = getBirthdateTextField().getText();

		if( getAgeTextField().getText().equals(""))
			array[5] = "0";
		else
			array[5] = getAgeTextField().getText();
		array[6] = "0";
		array[7] = "0";
		array[8] = "0";
		if(flag == true) {
			studentModel.addRow(array);
			resetAll();
			JOptionPane.showMessageDialog(this, "Student Entry is added successfully.", "Message Dialog", JOptionPane.PLAIN_MESSAGE);
		}
		else {
			/*JOptionPane.showMessageDialog(this, "Entry Can not be added, first name and last name can not be empty",
					"Error Message", JOptionPane.ERROR_MESSAGE);*/
		}

	}                                        

	public String valueSelectedRButton() {
		if(rButtonValue == 1)
			return "male";
		else if(rButtonValue == 2)
			return "female";
		else 
			return "unknown";
	}

	public int SetRButtonValue(int val) {
		rButtonValue = val;
		return rButtonValue;
	}

	private void maleRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {                                               
		// TODO add your handling code here:
		if(((javax.swing.JRadioButton) evt.getSource()).isSelected()) {
			SetRButtonValue(1);
		}
	}                                              

	private void femaleRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {                                               
		// TODO add your handling code here:
		if(((javax.swing.JRadioButton) evt.getSource()).isSelected()) {
			SetRButtonValue(2);
		}
	}  

	/**
	 * @param id the id to set
	 */
	public static void setId(int id) {
		AddStudentEntry.id = id;
	}

	/**
	 * @return the ageTextField
	 */
	public javax.swing.JTextField getAgeTextField() {
		return ageTextField;
	}

	/**
	 * @return the birthdateTextField
	 */
	public javax.swing.JTextField getBirthdateTextField() {
		return birthdateTextField;
	}

	/**
	 * @return the femaleRadioButton
	 */
	public javax.swing.JRadioButton getFemaleRadioButton() {
		return femaleRadioButton;
	}

	/**
	 * @return the firstNameTextfield
	 */
	public javax.swing.JTextField getFirstNameTextfield() {
		return firstNameTextfield;
	}

	/**
	 * @return the lastNameTextfield
	 */
	public javax.swing.JTextField getLastNameTextfield() {
		return lastNameTextfield;
	}

	/**
	 * @return the maleRadioButton
	 */
	public javax.swing.JRadioButton getMaleRadioButton() {
		return maleRadioButton;
	}



	/**
	 * @return the id
	 */
	public static int getId() {
		return id;
	}



	// Variables declaration - do not modify  
	private int rButtonValue;
	private javax.swing.JLabel ageLabel;
	private javax.swing.JTextField ageTextField;
	private javax.swing.JLabel birthdateLabel;
	private javax.swing.JTextField birthdateTextField;
	private javax.swing.JButton clearButton;
	private javax.swing.JRadioButton femaleRadioButton;
	private javax.swing.JLabel firstNameLabel;
	private javax.swing.JTextField firstNameTextfield;
	private javax.swing.JLabel genderLabel;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel lastNameLabel;
	private javax.swing.JTextField lastNameTextfield;
	private javax.swing.JRadioButton maleRadioButton;
	private javax.swing.JButton okButton;
	// End of variables declaration                   
}
