import java.awt.Color;
import java.io.File;
import java.util.Arrays;

import javax.swing.*;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sankhe
 */
public class AdminLogin extends javax.swing.JPanel {

	/**
	 * Creates new form AdminLogin
	 */

	/*
	 *  Please change the path to the folder where Frugal Lab logo image is stored.
	 *       
	 */
	 File file=new File(".");
	  private String path = file.getAbsolutePath().replace(".", "").trim() + "audioAndimages/";
	  private String pathToFrugalLabLogo = path.replace("\\", "/");
	//private String pathToFrugalLabLogo = "C:/Users/sankhe/Desktop/JAVA/CD_contents/Contents/JavaBook/image/";

	/*
	 * 				  ^  ^  ^  ^  ^  ^  ^  ^  ^
	 *                |  |  |  |  |  |  |  |  | 
	 */

	public AdminLogin() {
		initComponents();
		Color c = new Color(243, 247, 110);
		setBackground(c);
		Border compound, raisedbevel, loweredbevel;
		raisedbevel = BorderFactory.createRaisedBevelBorder();
		loweredbevel = BorderFactory.createLoweredBevelBorder();
		Border redline = BorderFactory.createLineBorder(Color.red, 10);
		//This creates a nice frame.
		compound = BorderFactory.createCompoundBorder(raisedbevel, loweredbevel);
		setBorder(compound);
		//Add a red outline to the frame.
		compound = BorderFactory.createCompoundBorder(
				redline, compound);
		setBorder(compound);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		userNameLabel = new javax.swing.JLabel();
		userNameTextfield = new javax.swing.JTextField();
		passwordLabel = new javax.swing.JLabel();
		passwordField = new javax.swing.JPasswordField();
		loginButton = new javax.swing.JButton();
		frugalLabLogo = new javax.swing.JLabel();

		setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				formKeyPressed(evt);
			}
		});
		setLayout(new java.awt.GridBagLayout());

		userNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		userNameLabel.setText("User Name");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.ipadx = 30;
		gridBagConstraints.ipady = 14;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 54, 0, 0);
		add(userNameLabel, gridBagConstraints);

		userNameTextfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		userNameTextfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
		userNameTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				userNameTextfieldKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.ipadx = 150;
		gridBagConstraints.ipady = 10;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(25, 45, 0, 0);
		add(userNameTextfield, gridBagConstraints);

		passwordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		passwordLabel.setText("Password");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 34;
		gridBagConstraints.ipady = 14;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 54, 0, 0);
		add(passwordLabel, gridBagConstraints);

		passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
		passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				passwordFieldKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.ipadx = 150;
		gridBagConstraints.ipady = 10;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(11, 45, 0, 0);
		add(passwordField, gridBagConstraints);

		loginButton.setBackground(new java.awt.Color(0, 153, 0));
		loginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		loginButton.setForeground(new java.awt.Color(51, 0, 51));
		loginButton.setText("LOGIN");
		loginButton.setToolTipText("click me to login in");
		loginButton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N
		loginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginButtonActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.ipadx = 87;
		gridBagConstraints.ipady = 10;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(23, 122, 22, 0);
		add(loginButton, gridBagConstraints);

		String str = pathToFrugalLabLogo+"frugalLab logo.png";
		try {
			ImageIcon pic = new ImageIcon(str);
			frugalLabLogo.setIcon(pic); // NOI18N 
		}
		catch(Exception e) {
			System.out.println("An error has occurred while reading image file. Check that file exists and is in the correct directory.");
			System.exit(1);
		}
		frugalLabLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 7;
		gridBagConstraints.ipadx = -4;
		gridBagConstraints.ipady = -9;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(30, 35, 0, 38);
		add(frugalLabLogo, gridBagConstraints);
	}// </editor-fold>                        

	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
		doNextEvent();
	}                                           

	private void formKeyPressed(java.awt.event.KeyEvent evt) {                                
		// TODO add your handling code here:
	}                               

	private void userNameTextfieldKeyPressed(java.awt.event.KeyEvent evt) {                                             
		// TODO add your handling code here:
		if(evt.getKeyCode() == 10)
			doNextEvent();
	}                                            

	private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {                                         
		if(evt.getKeyCode() == 10)
			doNextEvent();
	}                                        

	public void doNextEvent() {
		boolean flag = validateLogin();
		if(flag == true) {
			MainFrame.layCard.show(MainFrame.getTopPanel(), "2");
			clearUserInput();
		}
		else {
			JOptionPane.showMessageDialog(this, "Invalid password. Try again.",
					"Error Message", JOptionPane.ERROR_MESSAGE);
		}
	}

	public void clearUserInput() {
		userNameTextfield.setText("");
		passwordField.setText("");
	}

	public void startFocusListeners() {
		this.setFocusable(true);
		this.requestFocusInWindow();
	}

	public boolean validateLogin() {

		if(userNameTextfield.getText().equals("root")) {
			char[] input = passwordField.getPassword();
			if (isPasswordCorrect(input)) {
				return true; 
			}
		}
		return false;
	}

	private boolean isPasswordCorrect(char[] input) {
		boolean isCorrect = true;
		char[] correctPassword = { 'r', 'o', 'o', 't'};
		if (input.length != correctPassword.length) {
			isCorrect = false;
		} else {
			isCorrect = Arrays.equals (input, correctPassword);
		}
		//Zero out the password.
		Arrays.fill(correctPassword,'0');
		return isCorrect;
	}

	// Variables declaration - do not modify                     
	private javax.swing.JLabel frugalLabLogo;
	private javax.swing.JButton loginButton;
	private javax.swing.JPasswordField passwordField;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JLabel userNameLabel;
	private javax.swing.JTextField userNameTextfield;
	// End of variables declaration                   
}
