
import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sankhe
 */
public class DeleteStudentEntry extends javax.swing.JPanel {
	StudentModel model;
	/**
	 * Creates new form DeleteStudentEntry
	 */
	public DeleteStudentEntry() {
		initComponents();
		Color c = new Color(183, 238, 242);
		setBackground(c);
		Border compound, raisedbevel, loweredbevel;
		raisedbevel = BorderFactory.createRaisedBevelBorder();
		loweredbevel = BorderFactory.createLoweredBevelBorder();
		Border redline = BorderFactory.createLineBorder(Color.yellow, 10);
		//This creates a nice frame.
		compound = BorderFactory.createCompoundBorder(raisedbevel, loweredbevel);
		setBorder(compound);
		//Add a red outline to the frame.
		compound = BorderFactory.createCompoundBorder(
				redline, compound);
		setBorder(compound);
		delete = this;
		model = MainFrame.getStudentModel();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		fnameLabel = new javax.swing.JLabel();
		lnameLabel = new javax.swing.JLabel();
		fnameTextField = new javax.swing.JTextField();
		lnameTextField = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setLayout(new java.awt.GridBagLayout());

		fnameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		fnameLabel.setText("First Name");
		fnameLabel.setToolTipText("");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.ipadx = 8;
		gridBagConstraints.ipady = 10;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(66, 88, 0, 0);
		add(fnameLabel, gridBagConstraints);

		lnameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		lnameLabel.setText("Last Name");
		lnameLabel.setToolTipText("");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.ipadx = 8;
		gridBagConstraints.ipady = 10;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(6, 89, 0, 0);
		add(lnameLabel, gridBagConstraints);

		fnameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		fnameTextField.setToolTipText("");
		fnameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
		fnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				fnameTextFieldKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 143;
		gridBagConstraints.ipady = 18;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(67, 18, 0, 0);
		add(fnameTextField, gridBagConstraints);

		lnameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		lnameTextField.setToolTipText("");
		lnameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
		lnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				lnameTextFieldKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.ipadx = 143;
		gridBagConstraints.ipady = 18;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(7, 18, 0, 0);
		add(lnameTextField, gridBagConstraints);

		jButton1.setBackground(new java.awt.Color(0, 153, 0));
		jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jButton1.setText("Delete Entry");
		jButton1.setToolTipText("click me to delete the student entry");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.ipadx = 88;
		gridBagConstraints.ipady = 22;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(18, 111, 0, 0);
		add(jButton1, gridBagConstraints);

		jButton2.setBackground(new java.awt.Color(255, 0, 0));
		jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jButton2.setText("Back");
		jButton2.setToolTipText("click me to go back");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.ipadx = 41;
		gridBagConstraints.ipady = 16;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(33, 98, 21, 24);
		add(jButton2, gridBagConstraints);
	}// </editor-fold>                        

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:MainFrame.layCard.show(MainFrame.getTopPanel(), "2");
		MainFrame.layCard.show(MainFrame.getTopPanel(), "2");
	}
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:MainFrame.layCard.show(MainFrame.getTopPanel(), "2")
		String str1 = fnameTextField.getText();
		String str2 = lnameTextField.getText();
		boolean flag = true;
		if(str1.equals(""))
		{
			JOptionPane.showMessageDialog(this, "Please enter first name.",
					"Error Message", JOptionPane.ERROR_MESSAGE);
			flag = false;
		}
		if(str2.equals(""))
		{
			JOptionPane.showMessageDialog(this, "Please enter last name.",
					"Error Message", JOptionPane.ERROR_MESSAGE);
			flag = false;
		}
		if(flag == true) {
			int del = model.deleteRow(str1, str2);
			if(del > 0) {
				resetAll();
				String str = "Student Entry for" + "\"" + str1 + " " + str2+ "\"" + " is deleted successfully";
				JOptionPane.showMessageDialog(this, str, "Message Dialog", JOptionPane.PLAIN_MESSAGE);
			}
			else {
				String str = "Student Entry for" + "\"" + str1 + " " + str2+ "\"" + " is does not exist";
				JOptionPane.showMessageDialog(this, str, "Error Message", JOptionPane.ERROR_MESSAGE);
			}
		}
		
	}

	private void fnameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {                                          
		// TODO add your handling code here:
		if(evt.getKeyCode() == 10) {
			// add event later "deleted successfully"
		}
	}                                         

	public void resetAll() {
		fnameTextField.setText("");
        lnameTextField.setText("");
	}
	
	private void lnameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {                                          
		// TODO add your handling code here:
		if(evt.getKeyCode() == 10) {
			//// add event later "deleted successfully"
		}

	}              

	public static DeleteStudentEntry getObjectDeleteEntry() {
		return delete;
	}

	
	/**
	 * @return the fnameTextField
	 */
	public javax.swing.JTextField getFnameTextField() {
		return fnameTextField;
	}

	/**
	 * @return the lnameTextField
	 */
	public javax.swing.JTextField getLnameTextField() {
		return lnameTextField;
	}


	private static DeleteStudentEntry delete;
	// Variables declaration - do not modify                     
	private javax.swing.JLabel fnameLabel;
	private javax.swing.JTextField fnameTextField;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel lnameLabel;
	private javax.swing.JTextField lnameTextField;
	// End of variables declaration                   
}
